version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./shared/audio:/app/shared/audio
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  worker:
    build: ./worker
    container_name: worker
    restart: always
    volumes:
      - ./shared/audio:/app/shared/audio
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
